# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d6b63eb1aa4b87fe111d1e353c03e6f2743f6f2d61c7f2c04b7c33045a1162df48306c529f9462673a4409119c63916b23415471b25e591ce6467fdf4abaa34

test:
  secret_key_base: 91cb6d17a57383cffbee3756c768bb5c56421ec424cdf1216c7c6f3aec3634a4e88840e84fa41e68b35be8dc32a4b5814eb599da70798f342ae619157e56599a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
